const EMOJIS = [
    ':bomb::fire:',
    ':gem::palms_up_together:',
    ':rocket::chart_with_upwards_trend:',
    ':chart::star2:',
    ':fire::moneybag:',
    ':bar_chart::trophy:',
    ':first_place::money_with_wings:',
    ':globe_with_meridians::chart:',
    ':chart_with_upwards_trend::champagne:',
    ':briefcase::top:',
    ':bank::fire:',
    ':dart::chart:',
    ':trophy::moneybag:',
    ':ocean::bar_chart:',
    ':chart_with_upwards_trend::battery:',
    ':money_with_wings::globe_with_meridians:',
    ':stars::trophy:',
    ':checkered_flag::chart:',
    ':statue_of_liberty::chart_with_upwards_trend:',
    ':chart::rocket:',
    ':sun_with_face::moneybag:',
    ':roller_coaster::bar_chart:',
    ':money_with_wings::chart_with_upwards_trend::champagne_glass:',
    ':rocket::rainbow::last_quarter_moon_with_face:',
    ':rocket::chart::chart_with_upwards_trend:',
    ':star2::moneybag::trophy:',
    ':muscle::top::chart:',
    ':chart_with_upwards_trend::champagne::champagne_glass:',
    ':money_with_wings::ocean::person_surfing:',
    ':first_place::bar_chart::moneybag:',
    ':fire::moneybag::star2:',
    ':globe_with_meridians::chart_with_upwards_trend::rocket:',
    ':chart::boom::top:',
    ':bar_chart::bank::fire:',
    ':dart::chart_with_upwards_trend::money_with_wings:',
    ':tada::moneybag::muscle:',
    ':race_car::dash::chart:',
    ':stars::chart_with_upwards_trend::trophy:',
    ':briefcase::fire::bar_chart:',
    ':helicopter::chart_with_upwards_trend::moneybag:',
    ':four_leaf_clover::bar_chart::first_place:',
    ':tophat::moneybag::chart_with_upwards_trend:',
    ':lion_face::top::bar_chart:',
    ':gem::chart::star2:',
    ':bow_and_arrow::dart::chart_with_upwards_trend:',
    ':trophy::money_with_wings::globe_with_meridians:',
    ':tropical_drink::beach::chart:',
    ':person_biking::dash::bar_chart:',
    ':sunrise::chart_with_upwards_trend::money_with_wings:',
    ':briefcase::star2::chart_with_upwards_trend:',
    ':chart_with_upwards_trend::moneybag::battery:',
    ':partying_face::chart::trophy:',
    ':rainbow::moneybag::bar_chart:',
    ':bar_chart::top::cruise_ship:',
    ':statue_of_liberty::money_with_wings::chart_with_upwards_trend:',
    ':bullettrain_front::chart::fire:',
    ':chart::sun_with_face::trophy:',
    ':mountain_snow::chart_with_upwards_trend::money_with_wings:',
    ':bar_chart::moneybag::beers:',
    ':palm_tree::chart::star2:',
    ':helicopter::globe_with_meridians::chart_with_upwards_trend:',
    ':race_car::checkered_flag::chart:',
    ':roller_coaster::chart_with_upwards_trend::moneybag:',
    ':confetti_ball::bar_chart::first_place:',
];

const PHRASES = [];

const random = (arr) => arr[Math.floor(Math.random() * arr.length)];
export const randomPhrase = () => random(PHRASES);
export const randomEmojis = () => random(EMOJIS);